Repository nextcloud/viewer, pull requests merged in 2019-08, with the labels that each got.

#191 Properly encode directory/filename in requests
  js/viewer.js
  js/viewer.js.map
  src/views/Viewer.vue
Labels: 4. to release, bug

#150 Add stable16 tests on master as well
  .drone.yml
Labels: 2. developing

#205 Add playsinline to video
  js/viewer.js
  js/viewer.js.map
  src/components/Videos.vue
Labels: 3. to review, bug

#206 Show filename in title
  js/viewer.js
  js/viewer.js.map
  src/views/Viewer.vue
Labels: 3. to review, enhancement

#208 Fix autocomplete under sidebar
  appinfo/info.xml
  js/viewer.js
  js/viewer.js.map
  package-lock.json
  package.json
  src/views/Viewer.vue
Labels: 3. to review, bug
