Repository nextcloud/viewer, pull requests merged in 2019-03, with the labels that each got.

#16 Add svg support
  package-lock.json
  package.json
  src/components/Images.vue
  src/models/images.js
Labels: 3. to review, enhancement

#20 Recalculate size on window resize
  package-lock.json
  package.json
  src/components/Images.vue
  src/components/Videos.vue
  src/mixins/Mime.js
  src/views/Viewer.vue
Labels: 3. to review, design, enhancement

#24 Simplify error message
  src/components/Error.vue
Labels: 3. to review, design

#29 Fixes/design/img bg border radius use modal max
  package-lock.json
  package.json
  src/components/Images.vue
  src/mixins/Mime.js
  src/services/FileList.js
  src/views/Viewer.vue
Labels: 3. to review, design, enhancement

#34 Fix/various
  package-lock.json
  package.json
  src/views/Viewer.vue
Labels: 3. to review, bug

#33 Use preview endpoint for images
  src/components/Images.vue
  src/views/Viewer.vue
Labels: 3. to review, enhancement

#35 Sort files
  src/views/Viewer.vue
Labels: 3. to review, bug

#36 Zoom scrolling enhancement
  src/components/Images.vue
  src/mixins/Mime.js
  src/views/Viewer.vue
Labels: 2. developing, design, enhancement

#38 Do not use preview for gifs
  src/components/Images.vue
  src/mixins/Mime.js
  src/views/Viewer.vue
Labels: 3. to review, bug

#49 Allow registering aliases without components
  src/models/videos.js
  src/views/Viewer.vue
Labels: 2. developing, bug, enhancement

#55 Fix display of tiny images
  js/viewer.js
  js/viewer.js.map
  src/components/Images.vue
Labels: 3. to review, bug

#56 Add drone webpack build check
  .drone.yml
  js/viewer.js
  js/viewer.js.map
  package-lock.json
  package.json
  webpack.dev.js
Labels: 2. developing
