Repository nextcloud/viewer, pull requests merged in 2019-05, with the labels that each got.

#94 Cleanup and manage video errors
  js/viewer.js
  js/viewer.js.map
  src/components/Videos.vue
  src/models/file.js
  src/views/Viewer.vue
Labels: 3. to review, bug

#95 Nextcloud-vue 0.11.1 compatibility and sidebar fix
  js/viewer.js
  js/viewer.js.map
  package-lock.json
  package.json
  src/views/Viewer.vue
Labels: 3. to review, bug

#100 Stable16 cypress/tests update
  .drone.yml
  cypress.json
  cypress/integration/files.spec.js
  cypress/integration/image.png.spec.js
  cypress/integration/images.spec.js
Labels: 3. to review

#98 [stable16] Do not fetch the full list of directory if the handler do not belong to a group
  js/viewer.js
  js/viewer.js.map
  src/views/Viewer.vue
Labels: 3. to review

#99 [stable16] Expose file-id prop
  js/viewer.js
  js/viewer.js.map
  src/mixins/Mime.js
  src/views/Viewer.vue
Labels: 3. to review

#101 Simplify development setup instructions
  README.md
Labels: 3. to review, enhancement
