Repository nextcloud/viewer, pull requests merged in 2019-06, with the labels that each got.

#142 Use more applicable icon for 'Open sidebar'
  cypress/integration/image-small.png.spec.js
  cypress/integration/image.gif.spec.js
  cypress/integration/image.png.spec.js
  cypress/integration/image.svg.spec.js
  cypress/integration/images.spec.js
  cypress/integration/video.mkv.spec.js
  cypress/integration/video.mp4.spec.js
  cypress/integration/video.ogv.spec.js
  cypress/integration/video.webm.spec.js
  cypress/integration/videos.spec.js
  js/viewer.js
  js/viewer.js.map
  src/assets/menu-sidebar-white.svg
  src/assets/share-white.svg
  src/views/Viewer.vue
Labels: 3. to review, backport-request, design, enhancement, papercut

#146 Fix sidebar position when scrolling in file list
  js/viewer.js
  js/viewer.js.map
  src/views/Viewer.vue
Labels: 3. to review, backport-request, bug

#143 Save video volume setting to LocalStorage
  js/viewer.js
  js/viewer.js.map
  src/components/Videos.vue
Labels: 2. developing, enhancement

#149 Do not open the same file
  js/viewer.js
  js/viewer.js.map
  src/views/Viewer.vue
Labels: 3. to review
