Repository nextcloud/viewer, pull requests merged in 2020-03, with the labels that each got.

#421 Fix trying to open the sidebar when not available
  js/viewer.js
  js/viewer.js.map
  src/views/Viewer.vue
Labels: 3. to review, bug, javascript

#423 Move cypress to gh actions
  .drone.yml
  .eslintrc.js
  .github/workflows/cypress.yml
  cypress/integration/images-custom-list-loadmore.spec.js
  js/viewer.js
  js/viewer.js.map
  package-lock.json
  package.json
Labels: 3. to review

#428 [stable18] Fix trying to open the sidebar when not available
  js/viewer.js
  js/viewer.js.map
  src/views/Viewer.vue
Labels: 3. to review, bug

#443 Migrate to Plyr & fix video preloading
  cypress/integration/videos.spec.js
  img/plyr.svg
  js/viewer.js
  js/viewer.js.map
  package-lock.json
  package.json
  src/components/Videos.vue
Labels: 3. to review, bug, enhancement

#449 Fix public preview url cropping
  js/viewer.js
  js/viewer.js.map
  src/mixins/PreviewUrl.js
Labels: 3. to review, backport-request, bug

#450 [stable18] Fix public preview url cropping
  js/viewer.js
  js/viewer.js.map
  src/mixins/PreviewUrl.js
Labels: 3. to review, bug
