Repository nextcloud/viewer, pull requests merged in 2020-10, with the labels that each got.

#626 Fix player controls on Firefox
  .eslintrc.js
  img/plyr.svg
  js/viewer-main.js
  js/viewer-main.js.map
  src/components/Videos.vue
  src/main.js
  webpack.js
Labels: 3. to review, backport-request, bug, high

#628 Make div display: none
  js/viewer-main.js
  js/viewer-main.js.map
  src/main.js
Labels: 3. to review, backport-request, bug

#630 Use node lts 12
  .github/workflows/cypress.yml
  .github/workflows/lint.yml
  .github/workflows/node.yml
  package.json
Labels: 3. to review, enhancement

#631 Fix theming chaining
  .eslintrc.js
  js/viewer-main.js
  js/viewer-main.js.map
  src/views/Viewer.vue
Labels: 3. to review, backport-request, bug

#642 Fix cypress branch
  .github/workflows/cypress.yml
  cypress/docker-compose.yml
  cypress/initserver.sh
  cypress/start.sh
  js/viewer-main.js
  js/viewer-main.js.map
  package-lock.json
  package.json
Labels: 3. to review, backport-request, bug

#647 Add option to prevent loop on file list
  js/viewer-main.js
  js/viewer-main.js.map
  src/services/Viewer.js
  src/views/Viewer.vue
Labels: 3. to review, enhancement

#662 Fix component click outside and cleanup structure
  cypress/integration/audio.mpeg.spec.js
  cypress/integration/audio.ogg.spec.js
  cypress/integration/audios.spec.js
  cypress/integration/delete.spec.js
  cypress/integration/files-shares.spec.js
  cypress/integration/image-small.png.spec.js
  cypress/integration/image.gif.spec.js
  cypress/integration/image.heic.spec.js
  cypress/integration/image.png.spec.js
  cypress/integration/image.svg.spec.js
  cypress/integration/images-custom-list-loadmore.spec.js
  cypress/integration/images-custom-list.spec.js
  cypress/integration/images.spec.js
  cypress/integration/sidebar.spec.js
  cypress/integration/video.mkv.spec.js
  cypress/integration/video.mp4.spec.js
  cypress/integration/video.ogv.spec.js
  cypress/integration/video.webm.spec.js
  cypress/integration/videos.spec.js
  js/viewer-main.js
  js/viewer-main.js.map
  src/views/Viewer.vue
Labels: 4. to release, backport-request, bug, regression
