Repository nextcloud/viewer, pull requests merged in 2020-08, with the labels that each got.

#497 add onPrev, onNext, and onClose callbacks
  js/viewer-main.js
  js/viewer-main.js.map
  package-lock.json
  package.json
  src/services/FilesActionHandler.js
  src/services/Viewer.js
  src/views/Viewer.vue
Labels: 4. to release, enhancement

#546 Fix zoom
  cypress/integration/image.svg.spec.js
  js/viewer-main.js
  js/viewer-main.js.map
  src/components/Images.vue
Labels: 3. to review, bug, regression

#566 Add PHP doc for event
  lib/Event/LoadViewer.php
Labels: 4. to release, enhancement

#576 Bump cypress to 5.0.0
  cypress/integration/files-shares.spec.js
  cypress/integration/image-small.png.spec.js
  cypress/integration/image.gif.spec.js
  cypress/integration/image.png.spec.js
  cypress/integration/image.svg.spec.js
  cypress/integration/images-custom-list-loadmore.spec.js
  cypress/integration/images-custom-list.spec.js
  cypress/integration/images.spec.js
  cypress/integration/sidebar.spec.js
  cypress/integration/video.mkv.spec.js
  cypress/integration/video.mp4.spec.js
  cypress/integration/video.ogv.spec.js
  cypress/integration/video.webm.spec.js
  cypress/integration/videos.spec.js
  cypress/support/commands.js
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#581 Set the X-Requested-With header on dav requests
  js/viewer-main.js
  js/viewer-main.js.map
  src/services/DavClient.js
Labels: 3. to review, enhancement

#570 Show proper error if the file doesn't have a handler
  js/viewer-main.js
  js/viewer-main.js.map
  package-lock.json
  package.json
  src/views/Viewer.vue
  webpack.js
Labels: 4. to release, enhancement

#586 [stable18] Set the X-Requested-With header on dav requests
  js/viewer.js
  js/viewer.js.map
  src/services/DavClient.js
Labels: 3. to review, bug
