Repository nextcloud/viewer, pull requests merged in 2020-07, with the labels that each got.

#529 Use IBootstrap for the app bootstrap
  appinfo/app.php
  lib/AppInfo/Application.php
Labels: 4. to release

#544 Fix cypress
  .github/workflows/cypress.yml
Labels: 3. to review, backport-request, bug

#543 Auto calc img size and center
  cypress/integration/image-small.png.spec.js
  cypress/integration/image.gif.spec.js
  cypress/integration/image.png.spec.js
  cypress/integration/images-custom-list-loadmore.spec.js
  cypress/integration/images-custom-list.spec.js
  cypress/integration/images.spec.js
  src/components/Images.vue
  src/views/Viewer.vue
Labels: 2. developing, enhancement, performances

#552 Fix babel
  package-lock.json
  package.json
Labels: 3. to review, bug, dependencies

#553 Use babel-loader-exclude-node-modules-except
  .github/workflows/phpunit.yml
  composer.lock
  cypress/integration/sidebar.spec.js
  js/viewer-main.js
  js/viewer-main.js.map
  package-lock.json
  package.json
  src/views/Viewer.vue
  webpack.js
Labels: 3. to review, dependencies, enhancement

#558 Move to webpack vue global config & bump deps
  .gitignore
  js/viewer-main.js
  js/viewer-main.js.map
  js/viewer.js.map
  lib/Listener/LoadViewerScript.php
  package-lock.json
  package.json
  src/components/Images.vue
  src/components/Videos.vue
  src/mixins/Mime.js
  src/models/file.js
  src/utils/davUtils.js
  src/views/Viewer.vue
  stylelint.config.js
  webpack.common.js
  webpack.dev.js
  webpack.js
  webpack.prod.js
Labels: 3. to review, technical debt
