Repository nextcloud/viewer, pull requests merged in 2020-02, with the labels that each got.

#378 Adjust tests syntax & formatting
  .github/workflows/lint.yml
  .github/workflows/node.yml
Labels: backport-request

#383 Use actions from tutorial
  .github/workflows/lint.yml
  .github/workflows/node.yml
Labels: 3. to review, backport-request

#384 [stable17] Use actions from tutorial
  .drone.yml
  .github/workflows/dependabot-approve.yml
  .github/workflows/lint.yml
  .github/workflows/node.yml
Labels: 3. to review, backport-request

#387 Move cypress to github actions
  .drone.yml
  .github/workflows/cypress.yml
Labels: 3. to review

#395 Revert "Fix url escaping"
  js/viewer.js
  js/viewer.js.map
  package-lock.json
  package.json
  src/services/FileInfo.js
  src/services/FileList.js
  src/utils/fileUtils.js
Labels: 3. to review, bug

#396 [stable18] Revert "Fix url escaping"
  js/viewer.js
  js/viewer.js.map
  package-lock.json
  package.json
  src/services/FileInfo.js
  src/services/FileList.js
  src/utils/fileUtils.js
Labels: 3. to review, bug

#394 Change sidebar file while changing file in slideshow
  cypress/integration/sidebar.spec.js
  js/viewer.js
  js/viewer.js.map
  src/views/Viewer.vue
Labels: 3. to review, backport-request, enhancement

#405 [stable18] Change sidebar file while changing file in slideshow
  cypress/integration/sidebar.spec.js
  js/viewer.js
  js/viewer.js.map
  src/views/Viewer.vue
Labels: 3. to review, enhancement
