Repository nextcloud/viewer, pull requests merged in 2020-01, with the labels that each got.

#329 Properly generate fileinfo containing array data
  js/viewer.js
  js/viewer.js.map
  src/utils/fileUtils.js
Labels: 3. to review, bug

#335 Allow to provide a custom files list
  cypress/integration/images-custom-list.spec.js
  cypress/support/commands.js
  js/viewer.js
  js/viewer.js.map
  src/services/Viewer.js
  src/views/Viewer.vue
Labels: 4. to release, enhancement, high

#338 Fix sidebar open
  cypress/integration/images-custom-list-loadmore.spec.js
  cypress/integration/sidebar.spec.js
  js/viewer.js
  js/viewer.js.map
  src/components/Videos.vue
  src/views/Viewer.vue
Labels: 3. to review, bug, integration

#342 Merge pull request #342 from nextcloud/master
  cypress/integration/images-custom-list-loadmore.spec.js
  cypress/integration/sidebar.spec.js
  js/viewer.js
  js/viewer.js.map
  package-lock.json
  package.json
  src/components/Videos.vue
  src/views/Viewer.vue
Labels: 3. to review, high

#355 Fix sidebar content resize
  js/viewer.js
  js/viewer.js.map
  src/mixins/Mime.js
Labels: 3. to review, backport-request, bug, high

#367 GitHub actions/lint
  .github/workflows/lint.yml
  composer.json
Labels: 3. to review, backport-request, enhancement

#357 Fix url escaping
  js/viewer.js
  js/viewer.js.map
  package-lock.json
  package.json
  src/services/FileInfo.js
  src/services/FileList.js
  src/utils/fileUtils.js
Labels: 3. to review, backport-request, bug

#370 Fix url escaping
  js/viewer.js
  js/viewer.js.map
  package-lock.json
  package.json
  src/services/FileInfo.js
  src/services/FileList.js
  src/utils/fileUtils.js
Labels: 3. to review, enhancement
