Repository nextcloud/viewer, pull requests merged in 2021-06, with the labels that each got.

#927 fix: fullscreen for Firefox
  js/viewer-main.js
  js/viewer-main.js.map
  src/components/Videos.vue
Labels: 3. to review, backport-request, bug

#899 Use physical pixel size for preview resolution
  js/viewer-main.js
  js/viewer-main.js.map
  src/mixins/PreviewUrl.js
Labels: 4. to release, backport-request, bug

#913 React to sidebar events from nextcloud-bus
  js/viewer-main.js
  js/viewer-main.js.map
  package-lock.json
  package.json
  src/views/Viewer.vue
Labels: 3. to review, enhancement

#955 Bump deps and use npm7
  .github/workflows/cypress.yml
  .github/workflows/lint.yml
  .github/workflows/node.yml
  js/viewer-main.js
  js/viewer-main.js.LICENSE.txt
  js/viewer-main.js.map
  package-lock.json
  package.json
  stylelint.config.js
Labels: 3. to review
