Repository nextcloud/viewer, pull requests merged in 2021-04, with the labels that each got.

#841 Fix fullscreen
  js/viewer-main.js
  js/viewer-main.js.LICENSE.txt
  js/viewer-main.js.map
  src/components/Videos.vue
Labels: 3. to review, backport-request, bug, design

#855 Add 'image/webp' mime type support
  cypress/fixtures/image.webp
  cypress/integration/image.webp.spec.js
  image.webp
  js/viewer-main.js
  js/viewer-main.js.map
  src/models/images.js
Labels: 3. to review, enhancement, file support request

#856 Limit scope of the icon white overwrite
  js/viewer-main.js
  js/viewer-main.js.map
  src/views/Viewer.vue
Labels: 3. to review, backport-request, bug

#859 [stable20] Limit scope of the icon white overwrite
  js/viewer-main.js
  js/viewer-main.js.map
  src/views/Viewer.vue
Labels: 3. to review, bug

#868 Fixes for naughty filenames
  cypress/integration/oddname.spec.js
  cypress/support/commands.js
  js/viewer-main.js
  js/viewer-main.js.map
  src/utils/fileUtils.js
Labels: 3. to review, backport-request, bug

#871 Delete image.webp
  image.webp
Labels: 3. to review
