Repository nextcloud/viewer, pull requests merged in 2021-05, with the labels that each got.

#872 [stable20] Fixes for naughty filenames
  cypress/integration/oddname.spec.js
  cypress/support/commands.js
  js/viewer-main.js
  js/viewer-main.js.map
  package-lock.json
  package.json
  src/mixins/PreviewUrl.js
Labels: 2. developing, bug

#880 clean: use eslint on oddname + use encodeFilePath
  cypress/integration/oddname/oddname.js
  js/viewer-main.js
  js/viewer-main.js.map
  src/utils/fileUtils.js
Labels: 3. to review

#923 Add fixup
  .github/workflows/fixup.yml
Labels: 4. to release, backport-request
