Repository nextcloud/viewer, pull requests merged in 2021-12, with the labels that each got.

#1081 Comply to new addScript API
  .eslintrc.js
  js/viewer-main.js
  js/viewer-main.js.LICENSE.txt
  js/viewer-main.js.map
  lib/Listener/LoadViewerScript.php
  package-lock.json
  package.json
  src/services/logger.js
  src/views/Viewer.vue
Labels: enhancement, 3. to review

#1088 Fix german (Sie) translations comming from nextcloud-vue
  js/viewer-main.js
  js/viewer-main.js.map
  package-lock.json
  package.json
  src/main.js
Labels: backport-request

#1097 Add engines support for cypress tests
  .github/workflows/cypress.yml
Labels: 3. to review, backport-request, technical debt

#1098 Speed up cypress by building only once
  .github/workflows/cypress.yml
Labels: 2. developing, technical debt

#1107 Always check for `OCA.Files` before using it (Fixes: #1106)
  js/viewer-main.js
  js/viewer-main.js.map
  src/views/Viewer.vue
Labels: bug, regression, 3. to review

#1113 Disable swiping on viewer video controls
  js/viewer-main.js
  js/viewer-main.js.map
  src/components/Videos.vue
Labels: bug, 3. to review, backport-request
