Repository nextcloud/viewer, pull requests merged in 2021-08, with the labels that each got.

#936 Remove deprecation on open method
  js/viewer-main.js
  js/viewer-main.js.map
  src/services/Viewer.js
Labels: 3. to review, enhancement

#987 Updating command-compile.yml workflow from template
  .github/workflows/command-compile.yml
Labels: dependencies

#1013 Update dependabot
  .github/workflows/dependabot-approve-merge.yml
Labels: backport-request
