Repository nextcloud/viewer, pull requests merged in 2021-11, with the labels that each got.

#1064 disable fade-out because of accessbility reasons
  js/viewer-main.js
  js/viewer-main.js.map
  src/views/Viewer.vue
Labels: enhancement, 3. to review, backport-request

#1068 Update npm and node engines versions
  package.json
Labels: dependencies

#1065 Update version on master
  appinfo/info.xml
  js/viewer-main.js
  js/viewer-main.js.map
  package.json
Labels: enhancement, 4. to release, dependencies

#1071 [stable22] Fix github actions
  .github/workflows/cypress.yml
  cypress/integration/image.heic.spec.js
  cypress/integration/oddname/oddname-image.spec.js
Labels: 3. to review, backport-request

#1072 [stable21] fix github actions
  .github/workflows/cypress.yml
  cypress/integration/image.heic.spec.js
  cypress/integration/oddname.spec.js
Labels: 3. to review

#1067 [stable22] disable fade-out because of accessbility reasons
  js/viewer-main.js
  js/viewer-main.js.map
  src/views/Viewer.vue
Labels: enhancement, 3. to review, backport-request
