Repository nextcloud/viewer, pull requests merged in 2022-10, with the labels that each got.

#1397 Create psalm.yml
  .github/workflows/psalm.yml
  composer.json
  composer.lock
  psalm.xml
  tests/psalm-baseline.xml
Labels: 3. to review, backport-request

#1406 [stable24] Bump terser and async
  js/viewer-main.js.map
  package-lock.json
Labels: bug, 3. to review, dependencies

#1407 [stable23] Bump terser and async
  js/viewer-main.js.map
  package-lock.json
Labels: bug, 3. to review, dependencies

#1423 Updating lint-php.yml workflow from template
  .github/workflows/lint-php.yml
Labels: dependencies

#1424 Updating lint-stylelint.yml workflow from template
  .github/workflows/lint-stylelint.yml
Labels: dependencies

#1425 Updating lint-php-cs.yml workflow from template
  .github/workflows/lint-php-cs.yml
Labels: dependencies

#1427 Updating psalm.yml workflow from template
  .github/workflows/psalm.yml
Labels: dependencies

#1426 Updating lint-eslint.yml workflow from template
  .github/workflows/lint-eslint.yml
Labels: dependencies

#1415 [stable24] Use preview for unsupported images
  cypress/fixtures/image-apng.png
  cypress/fixtures/image.ico
  cypress/integration/image-apng.cy.js
  cypress/integration/image.ico.cy.js
  js/viewer-main.js
  js/viewer-main.js.map
  src/components/Images.vue
  src/models/images.js
Labels: bug, regression, medium, 3. to review
