Repository nextcloud/viewer, pull requests merged in 2022-05, with the labels that each got.

#1236 Revert "[stable24] Improve preloading"
  js/viewer-main.js
  js/viewer-main.js.map
  src/components/Videos.vue
Labels: 4. to release

#1237 Revert "Revert "[stable24] Improve preloading""
  js/viewer-main.js
  js/viewer-main.js.map
  src/components/Videos.vue
Labels: 3. to review

#1229 Fix design update after 5 vue components updgrade
  cypress/fixtures/test-card.mp4
  cypress/fixtures/test-card.png
  cypress/integration/image.png.spec.js
  cypress/integration/image.webp.spec.js
  cypress/integration/visual-regression.spec.js
  cypress/snapshots/base/visual-regression.spec.js/image-base.png
  cypress/snapshots/base/visual-regression.spec.js/video-base.png
  js/viewer-main.js
  js/viewer-main.js.map
  src/components/Videos.vue
  src/mixins/Mime.js
  src/views/Viewer.vue
Labels: bug, regression, design, high, 3. to review, backport-request

#1246 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#1247 Use modern API to cancel requests
  js/viewer-main.js
  js/viewer-main.js.LICENSE.txt
  js/viewer-main.js.map
  src/utils/CancelableRequest.js
Labels: bug, 3. to review, javascript
