Repository nextcloud/viewer, pull requests merged in 2022-01, with the labels that each got.

#1119 Bump deps and audit fix
  .stylelintignore
  js/viewer-main.js
  js/viewer-main.js.map
  package-lock.json
  package.json
Labels: 4. to release, dependencies, security

#1120 Do not run against non-test files
  cypress.json
Labels: 3. to review

#1121 Disable swiping on viewer audio controls
  js/viewer-main.js
  js/viewer-main.js.map
  src/components/Audios.vue
Labels: bug, 4. to release, backport-request

#1133 Create block-merge-freeze.yml
  .github/workflows/block-merge-freeze.yml
Labels: 3. to review, backport-request

#1137 Update lint-php.yml
  .github/workflows/lint-php.yml
Labels: backport-request

#1147 Npm audit fix
  package-lock.json
Labels: enhancement, 3. to review, security

#1148 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#1151 Updating fixup.yml workflow from template
  .github/workflows/fixup.yml
Labels: dependencies
