Repository nextcloud/viewer, pull requests merged in 2022-08, with the labels that each got.

#1316 Update npm and node engines versions
  package.json
Labels: dependencies

#1295 allow to delete files with a shortcut
  js/viewer-main.js
  js/viewer-main.js.map
  src/views/Viewer.vue
Labels: enhancement, 4. to release

#1346 Fix tests
  cypress/e2e/download-share-disabled.cy.js
  cypress/e2e/download-share.cy.js
  cypress/e2e/non-dav-files.cy.js
  cypress/e2e/visual-regression.cy.js
  cypress/snapshots/base/visual-regression.cy.js/image-base.png
  cypress/snapshots/base/visual-regression.cy.js/image2-base.png
  cypress/snapshots/base/visual-regression.cy.js/non-dav-base.png
Labels: 4. to release
