Repository nextcloud/viewer, pull requests merged in 2022-04, with the labels that each got.

#1202 Let header buttons properly adapt to the viewer handler theme
  js/viewer-main.js
  js/viewer-main.js.map
  src/views/Viewer.vue
Labels: 3. to review

#1206 Properly cancel and reset ongoing streams when unmounting
  js/viewer-main.js
  js/viewer-main.js.map
  src/components/Audios.vue
  src/components/Videos.vue
  src/views/Viewer.vue
Labels: bug, 3. to review, backport-request, performances

#1211 Remove cypress-image-snapshot
  cypress/integration/delete.spec.js
  cypress/integration/download-share-disabled.spec.js
  cypress/integration/download-share.spec.js
  cypress/integration/files-shares.spec.js
  cypress/integration/image-small.png.spec.js
  cypress/integration/image.png.spec.js
  cypress/integration/image.svg.spec.js
  cypress/integration/image.webp.spec.js
  cypress/integration/images-custom-list-loadmore.spec.js
  cypress/integration/images-custom-list.spec.js
  cypress/integration/images.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  js/viewer-main.js
  js/viewer-main.js.map
  package-lock.json
  package.json
Labels: 4. to release, technical debt

#1224 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#1190 Replace deprecated String.prototype.substr()
  cypress/utils/index.js
Labels: 4. to release, technical debt

#1228 Improve preloading
  js/viewer-main.js
  js/viewer-main.js.map
  src/components/Videos.vue
Labels: 3. to review, backport-request
