Repository nextcloud/viewer, pull requests merged in 2022-07, with the labels that each got.

#1260 Move to cypress 10
  .github/workflows/cypress.yml
  cypress.config.js
  cypress.json
  cypress/e2e/audio.mpeg.cy.js
  cypress/e2e/audio.ogg.cy.js
  cypress/e2e/audios.cy.js
  cypress/e2e/delete.cy.js
  cypress/e2e/download-share-disabled.cy.js
  cypress/e2e/download-share.cy.js
  cypress/e2e/download.cy.js
  cypress/e2e/files-shares.cy.js
  cypress/e2e/files.cy.js
  cypress/e2e/image-small.png.cy.js
  cypress/e2e/image.gif.cy.js
  cypress/e2e/image.png.cy.js
  cypress/e2e/image.svg.cy.js
  cypress/e2e/image.webp.cy.js
  cypress/e2e/images-custom-list-loadmore.cy.js
  cypress/e2e/images-custom-list.cy.js
  cypress/e2e/images.cy.js
  cypress/e2e/oddname/oddname-audio.cy.js
  cypress/e2e/oddname/oddname-image.cy.js
  cypress/e2e/oddname/oddname-video.cy.js
  cypress/e2e/oddname/oddname.js
  cypress/e2e/sidebar.cy.js
  cypress/e2e/video.mkv.cy.js
  cypress/e2e/video.mp4.cy.js
  cypress/e2e/video.ogv.cy.js
  cypress/e2e/video.webm.cy.js
  cypress/e2e/videos.cy.js
  cypress/e2e/visual-regression.cy.js
  cypress/plugins/index.js
  cypress/snapshots/base/visual-regression.cy.js/image-base.png
  cypress/snapshots/base/visual-regression.cy.js/image2-base.png
  cypress/snapshots/base/visual-regression.cy.js/video-base.png
  cypress/snapshots/base/visual-regression.spec.js/image-base.png
  cypress/snapshots/base/visual-regression.spec.js/image2-base.png
  cypress/snapshots/base/visual-regression.spec.js/video-base.png
  cypress/support/e2e.js
  package-lock.json
  package.json
Labels: 4. to release, dependencies

#1274 [stable23] Update @nextcloud/axios and webdav to make AbortControler work
  js/viewer-main.js
  js/viewer-main.js.map
  package-lock.json
  package.json
Labels: bug, 4. to release

#1279 Always use the main background for the default theme
  js/viewer-main.js
  js/viewer-main.js.map
  src/views/Viewer.vue
Labels: bug, 3. to review, backport-request

#1273 Add `openWith` function to OCA.Viewer
  js/viewer-main.js
  js/viewer-main.js.map
  src/services/Viewer.js
  src/views/Viewer.vue
Labels: enhancement, 3. to review

#1290 Fix html validation of material design icons
  js/viewer-main.js
  js/viewer-main.js.map
  src/views/Viewer.vue
Labels: bug, 4. to release

#1281 Expose handler to allow CSS selectors
  js/viewer-main.js
  js/viewer-main.js.map
  src/views/Viewer.vue
Labels: bug, 2. developing

#1296 [stable24] Merge pull request #1273 from nextcloud/enh/open_with
  js/viewer-main.js
  js/viewer-main.js.LICENSE.txt
  js/viewer-main.js.map
  package-lock.json
  src/services/Viewer.js
  src/views/Viewer.vue
Labels: bug, 3. to review

#1305 [stable23] Merge pull request #1273 from nextcloud/enh/open_with
  js/viewer-main.js
  js/viewer-main.js.map
  src/services/Viewer.js
  src/views/Viewer.vue
Labels: 3. to review
