Repository nextcloud/viewer, pull requests merged in 2023-08, with the labels that each got.

#1795 [master] Fix npm audit
  js/viewer-filerobot.js
  js/viewer-filerobot.js.map
  js/viewer-main.js
  js/viewer-main.js.map
  package-lock.json
Labels: 3. to review, dependencies

#1815 [master] Update cypress snapshots
  cypress/snapshots/base/visual-regression.cy.js/image.png
  cypress/snapshots/base/visual-regression.cy.js/image2.png
  cypress/snapshots/base/visual-regression.cy.js/non-dav.png
  cypress/snapshots/base/visual-regression.cy.js/video.png
Labels: 3. to review, dependencies, feedback-requested

#1806 Default to source if fileid is undefined
  js/viewer-filerobot.js
  js/viewer-filerobot.js.map
  js/viewer-main.js
  js/viewer-main.js.map
  src/views/Viewer.vue
Labels: enhancement, 3. to review, javascript

#1851 fix: Avoid issues when switching between versions
  js/viewer-main.js
  js/viewer-main.js.map
  src/views/Viewer.vue
Labels: bug, 3. to review, backport-request

#1845 [stable25] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1869 [stable27] Update cypress snapshots
  cypress/snapshots/base/visual-regression.cy.js/non-dav.png
Labels: 4. to release, dependencies

#1817 [stable25] Update cypress snapshots
  cypress/snapshots/base/visual-regression.cy.js/image-base.png
  cypress/snapshots/base/visual-regression.cy.js/image2-base.png
  cypress/snapshots/base/visual-regression.cy.js/non-dav-base.png
  cypress/snapshots/base/visual-regression.cy.js/video-base.png
Labels: 4. to release, dependencies, feedback-requested

#1870 [master] Update cypress snapshots
  cypress/snapshots/base/visual-regression.cy.js/image.png
  cypress/snapshots/base/visual-regression.cy.js/image2.png
  cypress/snapshots/base/visual-regression.cy.js/non-dav.png
  cypress/snapshots/base/visual-regression.cy.js/video.png
Labels: 4. to release, dependencies

#1863 Fix panning of zoomed images
  js/viewer-main.js
  js/viewer-main.js.map
  src/components/Images.vue
Labels: bug, 4. to release, backport-request

#1827 [stable26] Update cypress snapshots
  cypress/snapshots/base/visual-regression.cy.js/image.png
  cypress/snapshots/base/visual-regression.cy.js/image2.png
  cypress/snapshots/base/visual-regression.cy.js/non-dav.png
  cypress/snapshots/base/visual-regression.cy.js/video.png
Labels: 3. to review, dependencies, feedback-requested

#1818 Do not translate file alt-text
  js/viewer-main.js
  js/viewer-main.js.map
  src/components/Images.vue
Labels: 3. to review, feedback-requested

#1896 [master] Update cypress snapshots
  cypress/snapshots/base/visual-regression.cy.js/image.png
  cypress/snapshots/base/visual-regression.cy.js/image2.png
  cypress/snapshots/base/visual-regression.cy.js/non-dav.png
  cypress/snapshots/base/visual-regression.cy.js/video.png
Labels: 3. to review, dependencies

#1887 Improve image zooming (scroll wheel)
  js/viewer-main.js
  js/viewer-main.js.map
  src/components/Images.vue
  src/mixins/Mime.js
Labels: enhancement, 4. to release

#1929 fix: default action value & image public page style
  cypress/snapshots/base/visual-regression.cy.js/image.png
  cypress/snapshots/base/visual-regression.cy.js/image2.png
  cypress/snapshots/base/visual-regression.cy.js/non-dav.png
  cypress/snapshots/base/visual-regression.cy.js/video.png
  js/viewer-main.js
  js/viewer-main.js.map
  src/components/Images.vue
  src/views/Viewer.vue
Labels: 3. to review

#1942 Follow-up to: fix: default action value & image public page style
  js/viewer-main.js
  js/viewer-main.js.map
  src/components/Images.vue
Labels: bug, regression, 3. to review
