Repository nextcloud/viewer, pull requests merged in 2023-06, with the labels that each got.

#1695 fix: different cache path leads to cache miss
  .github/workflows/cypress.yml
Labels: bug, 3. to review, backport-request

#1707 Use new node event names
  js/viewer-main.js
  js/viewer-main.js.map
  src/components/ImageEditor.vue
  src/views/Viewer.vue
Labels: 3. to review, backport-request, javascript, technical debt

#1706 Fix size of progress container
  cypress/snapshots/base/visual-regression.cy.js/image.png
  cypress/snapshots/base/visual-regression.cy.js/image2.png
  cypress/snapshots/base/visual-regression.cy.js/non-dav.png
  cypress/snapshots/base/visual-regression.cy.js/video.png
  js/viewer-main.js
  js/viewer-main.js.map
  package-lock.json
  src/mixins/Plyr.scss
Labels: 4. to release, backport-request

#1694 chore: update workflows from templates
  .github/workflows/command-compile.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
Labels: 4. to release, dependencies, automated

#1718 [stable27] chore: update workflows from templates
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-compile.yml
  .github/workflows/command-rebase.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/psalm.yml
Labels: 3. to review, dependencies, automated

#1730 [stable27] Fix npm audit
  package-lock.json
Labels: 4. to release, dependencies

#1731 [stable24] Fix npm audit
  js/viewer-main.js
  js/viewer-main.js.map
  package-lock.json
Labels: 3. to review, dependencies

#1749 [master] Fix npm audit
  js/viewer-main.js
  js/viewer-main.js.LICENSE.txt
  js/viewer-main.js.map
  package-lock.json
Labels: 3. to review, dependencies

#1709 Use etag as cache buster
  js/viewer-components.js
  js/viewer-components.js.map
  js/viewer-filerobot.js
  js/viewer-filerobot.js.map
  js/viewer-main.js
  js/viewer-main.js.LICENSE.txt
  js/viewer-main.js.map
  js/viewer-plyr.js
  js/viewer-plyr.js.map
  package-lock.json
  package.json
  src/components/ImageEditor.vue
  src/components/Images.vue
  src/mixins/PreviewUrl.js
  src/services/DavClient.js
  src/services/FileInfo.js
  src/views/Viewer.vue
Labels: enhancement, 3. to review, backport-request, javascript

#1760 [master] Update cypress snapshots
  cypress/snapshots/base/visual-regression.cy.js/image.png
  cypress/snapshots/base/visual-regression.cy.js/image2.png
  cypress/snapshots/base/visual-regression.cy.js/non-dav.png
  cypress/snapshots/base/visual-regression.cy.js/video.png
Labels: 3. to review, dependencies

#1744 chore: update node engines to next LTS
  package.json
Labels: 3. to review, dependencies, automated

#1759 [stable27] Update cypress snapshots
  cypress/snapshots/base/visual-regression.cy.js/non-dav.png
Labels: 3. to review, dependencies

#1735 [stable26] fix: update npm scripts for visual regression snapshots update
  README.md
  cypress/snapshots/base/visual-regression.cy.js/image.png
  cypress/snapshots/base/visual-regression.cy.js/image2.png
  cypress/snapshots/base/visual-regression.cy.js/non-dav.png
  cypress/snapshots/base/visual-regression.cy.js/video.png
  package.json
Labels: 4. to release

#1761 feat(cypress): standard workflow
  .github/workflows/cypress.yml
  cypress.config.ts
  cypress/support/commands.js
Labels: 3. to review

#1764 Updating cypress.yml workflow from template
  .github/workflows/cypress.yml
Labels: dependencies, backport-request

#1771 [stable27] Update cypress snapshots
  cypress/snapshots/base/visual-regression.cy.js/non-dav.png
Labels: 3. to review, dependencies

#1773 feat: more typescript migration
  js/viewer-main.js
  js/viewer-main.js.map
  package-lock.json
  package.json
  src/components/ImageEditor.vue
  src/mixins/PreviewUrl.js
  src/models/file.js
  src/services/FileInfo.ts
  src/services/FileList.ts
  src/services/WebdavClient.ts
  src/utils/davUtils.ts
  src/utils/fileUtils.ts
  src/utils/numberUtil.ts
  src/views/Viewer.vue
  tsconfig.json
  webpack.config.ts
Labels: 3. to review, technical debt
