Repository nextcloud/viewer, pull requests merged in 2023-11, with the labels that each got.

#2065 feat: enable viewer for image/emf
  src/models/images.js
Labels: enhancement, 4. to release

#2067 chore: Bump @nextcloud/vue to v8.2.0
  cypress/e2e/sharing/download-share-disabled.cy.ts
  cypress/snapshots/base/visual-regression.cy.ts/image.png
  cypress/snapshots/base/visual-regression.cy.ts/image2.png
  cypress/snapshots/base/visual-regression.cy.ts/non-dav.png
  cypress/snapshots/base/visual-regression.cy.ts/video.png
  package-lock.json
  package.json
Labels: 3. to review

#2069 comment compile step
  .github/workflows/npm-audit-fix.yml
Labels: 3. to review

#2052 [master] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies, backport-request, feedback-requested

#2077 feat(viewer): allow async handler components
  src/views/Viewer.vue
Labels: enhancement, 3. to review

#2074 fix(video): video fullscreen on ios devices
  src/components/Videos.vue
Labels: bug, regression, 3. to review, backport-request

#2085 revert commenting compile step
  .github/workflows/npm-audit-fix.yml
Labels: 3. to review

#2087 fix: viewer handler check ordering
  js/viewer-main.js
  js/viewer-main.js.map
  src/views/Viewer.vue
Labels: 3. to review

#2088 Fix: Sorting filenames containing numbers
  js/viewer-main.js
  js/viewer-main.js.map
  src/utils/fileUtils.ts
Labels: bug, 3. to review, backport-request
