Repository nextcloud/viewer, pull requests merged in 2023-04, with the labels that each got.

#1622 add npm-audit-fix
  .github/workflows/npm-audit-fix.yml
Labels: 3. to review

#1630 [stable24] Fix npm audit
  js/viewer-main.js
  js/viewer-main.js.map
  package-lock.json
Labels: 3. to review, dependencies

#1629 update npm-audit-fix
  .github/workflows/npm-audit-fix.yml
Labels: bug, 3. to review
