Repository nextcloud/viewer, pull requests merged in 2023-07, with the labels that each got.

#1779 [stable24] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1778 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1777 [stable25] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1776 [stable26] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1775 [master] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1794 [stable27] Update cypress snapshots
  cypress/snapshots/base/visual-regression.cy.js/image.png
  cypress/snapshots/base/visual-regression.cy.js/image2.png
  cypress/snapshots/base/visual-regression.cy.js/non-dav.png
  cypress/snapshots/base/visual-regression.cy.js/video.png
Labels: 3. to review, dependencies

#1793 [stable25] Update cypress snapshots
  cypress/snapshots/base/visual-regression.cy.js/image-base.png
  cypress/snapshots/base/visual-regression.cy.js/image2-base.png
  cypress/snapshots/base/visual-regression.cy.js/non-dav-base.png
  cypress/snapshots/base/visual-regression.cy.js/video-base.png
Labels: 3. to review, dependencies

#1792 [master] Update cypress snapshots
  cypress/snapshots/base/visual-regression.cy.js/image.png
  cypress/snapshots/base/visual-regression.cy.js/image2.png
  cypress/snapshots/base/visual-regression.cy.js/non-dav.png
  cypress/snapshots/base/visual-regression.cy.js/video.png
Labels: 3. to review, dependencies

#1797 Send CSRF token in rawStat
  js/viewer-main.js
  js/viewer-main.js.map
  src/services/FileInfo.ts
Labels: bug, 3. to review, backport-request, javascript

#1763 Fix video player unusable on ios
  js/viewer-filerobot.js
  js/viewer-filerobot.js.map
  js/viewer-main.js
  js/viewer-main.js.map
  src/components/Videos.vue
Labels: bug, 3. to review, backport-request

#1819 fix fullscreen on ios
  js/viewer-main.js
  js/viewer-main.js.map
  src/components/Videos.vue
Labels: bug, 3. to review
