Repository nextcloud/viewer, pull requests merged in 2023-12, with the labels that each got.

#2093 fix: Disable view file in trashbin
  js/viewer-main.js
  js/viewer-main.js.map
  src/views/Viewer.vue
Labels: bug, 3. to review, backport-request

#2094 [stable28] fix: Disable view file in trashbin
  js/viewer-main.js
  js/viewer-main.js.map
  src/views/Viewer.vue
Labels: 3. to review

#2100 Disable image editor if accessibility switch is off
  js/viewer-main.js
  js/viewer-main.js.map
  src/views/Viewer.vue
Labels: 3. to review, backport-request, accessibility

#2102 [stable28] Disable image editor if accessibility switch is off
  js/viewer-main.js
  js/viewer-main.js.map
  src/views/Viewer.vue
Labels: 3. to review, accessibility

#2097 Preserve sort order
  js/viewer-main.js
  js/viewer-main.js.LICENSE.txt
  js/viewer-main.js.map
  src/services/FileSortingConfig.ts
  src/views/Viewer.vue
Labels: enhancement, 3. to review

#2106 chore: update workflows from templates
  .github/workflows/command-compile.yml
  .github/workflows/cypress.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
Labels: 4. to release, dependencies, backport-request, automated

#2107 [stable28] chore: update workflows from templates
  .github/workflows/command-compile.yml
  .github/workflows/cypress.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
Labels: 3. to review, dependencies, automated
