Repository nextcloud/viewer, pull requests merged in 2023-10, with the labels that each got.

#1980 fix: standalone check
  js/viewer-main.js
  js/viewer-main.js.map
  src/views/Viewer.vue
Labels: bug, regression, 3. to review

#2006 chore: recompile assets
  js/viewer-components.js
  js/viewer-components.js.map
  js/viewer-main.js
  js/viewer-main.js.LICENSE.txt
  js/viewer-main.js.map
  js/viewer-node_modules_nextcloud_dialogs_dist_legacy_mjs.js
  js/viewer-node_modules_nextcloud_dialogs_dist_legacy_mjs.js.map
Labels: 4. to release

#2010 fix(readme): Remove unnecessary instruction to enable the app
  README.md
Labels: 3. to review, technical debt

#2027 [master] Fix npm audit
  js/viewer-components.js
  js/viewer-components.js.map
  js/viewer-main.js
  js/viewer-main.js.LICENSE.txt
  js/viewer-main.js.map
Labels: 3. to review, dependencies

#2034 Cancel queued cypress jobs when repushing
  .github/workflows/cypress.yml
Labels: backport-request

#2048 [stable25] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies
