Repository nextcloud/viewer, pull requests merged in 2023-05, with the labels that each got.

#1654 fix: update npm scripts for visual regresison snapshots update
  README.md
  package.json
Labels: 3. to review

#1682 chore: update workflows from templates
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-compile.yml
  .github/workflows/command-rebase.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/psalm.yml
Labels: 4. to release, dependencies, automated

#1690 chore: update workflows from templates
  .github/workflows/block-merge-freeze.yml
Labels: 3. to review, dependencies, automated
