Repository nextcloud/viewer, pull requests merged in 2024-01, with the labels that each got.

#2115 fix(handlers): validate handlers before adding them
  js/viewer-main.js
  js/viewer-main.js.map
  src/services/Viewer.js
Labels: 3. to review

#2091 fix: make prev and next slides not focusable and aria-hidden
  cypress/e2e/a11y.cy.ts
  js/viewer-main.js
  js/viewer-main.js.map
  src/views/Viewer.vue
Labels: bug, 3. to review, backport-request, accessibility

#2112 fix: use filename to find current index
  js/viewer-main.js
  js/viewer-main.js.map
  src/services/Viewer.js
  src/views/Viewer.vue
Labels: enhancement, 4. to release

#2120 test(cy): use docker commands from @nextcloud/cypress
  cypress.config.ts
  cypress/dockerNode.ts
  package-lock.json
  package.json
Labels: 3. to review

#2123 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#2126 Update npm and node engines versions
  package.json
Labels: dependencies
