Repository nextcloud/viewer, pull requests merged in 2024-09, with the labels that each got.

#2453 chore(CI): Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#2461 [master] Update cypress snapshots
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/image.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/image2.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/non-dav.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/video.png
Labels: 3. to review, dependencies

#2462 [stable30] Update cypress snapshots
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/image.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/image2.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/non-dav.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/video.png
Labels: 3. to review, dependencies

#2467 fix: Adjust viewer for Nextcloud 31 public share UI
  css/index-fGu6wN-b.chunk.css
  css/main-59Rorz3q.chunk.css
  css/main-B8JMBDQI.chunk.css
  css/main-BQpYvOBl.chunk.css
  css/main-BT4PqNwX.chunk.css
  css/main-Bib0W53f.chunk.css
  css/main-Bq-oOeTE.chunk.css
  css/main-BqxICS9X.chunk.css
  css/main-CTwq7dfv.chunk.css
  css/main-CWJ2NyUp.chunk.css
  css/main-DELUg34d.chunk.css
  css/main-DXSti9TM.chunk.css
  css/main-DbVYYLtT.chunk.css
  css/main-DbamWgYd.chunk.css
  css/main-DduclpYy.chunk.css
  css/main-JMTTP9er.chunk.css
  css/main-Y8hU2k5s.chunk.css
  css/main-dRuNgPbA.chunk.css
  css/main-i-yDHPLj.chunk.css
  css/viewer-index.css
  css/viewer-main.css
  cypress/e2e/mixins/oddname.ts
  cypress/e2e/sharing/download-share-disabled.cy.ts
  cypress/e2e/sharing/download-share.cy.ts
  cypress/e2e/sharing/files-shares.cy.ts
  cypress/e2e/sharing/single-file-share.cy.ts
  cypress/support/commands.ts
  cypress/tsconfig.json
  js/viewer-main.mjs
  src/files_actions/viewerAction.ts
  src/global.d.ts
  src/services/FilesActionHandler.js
  src/services/LegacyFilesActionHandler.js
  src/shims.d.ts
  src/utils/fileUtils.ts
  src/views/Viewer.vue
  tsconfig.json
Labels: bug, 3. to review

#2496 fix(cypress): roboto loading check for visual regression
  cypress/e2e/visual-regression.cy.ts
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/image.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/image2.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/non-dav.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/video.png
Labels: 3. to review

#2479 [master] Update cypress snapshots
  .github/workflows/cypress-snapshot-update.yml
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/image.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/image2.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/non-dav.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/video.png
Labels: 3. to review, dependencies

#2500 [stable30] Update cypress snapshots
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/image.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/image2.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/non-dav.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/video.png
Labels: 3. to review, dependencies

#2502 [master] Update cypress snapshots
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/image.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/image2.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/non-dav.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/video.png
  cypress/support/commands.ts
Labels: 3. to review, dependencies

#2501 [stable29] Update cypress snapshots
  css/main-B6AIK0Xl.chunk.css
  css/viewer-main.css
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/image.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/image2.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/non-dav.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/video.png
  js/index-CCpXz4wq.chunk.mjs
  js/index-CCpXz4wq.chunk.mjs.map
  js/index-Mhl4DCn-.chunk.mjs
  js/index-Mhl4DCn-.chunk.mjs.map
  js/vendor.LICENSE.txt
  js/viewer-main.mjs
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#2493 fix: Only remove openfile from route when closing the viewer
  js/viewer-init.mjs
  js/viewer-init.mjs.map
  src/files_actions/viewerAction.ts
Labels: bug, 3. to review, backport-request, javascript

#2516 [stable30] fix: Only remove openfile from route when closing the viewer
  js/viewer-init.mjs
  js/viewer-init.mjs.map
  src/files_actions/viewerAction.ts
Labels: bug, 3. to review, javascript

#2523 chore(CI): Updating cypress.yml workflow from template
  .github/workflows/cypress.yml
Labels: 4. to release, dependencies

#2520 [stable30] Update cypress snapshots
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/non-dav.png
Labels: 3. to review, dependencies

#2519 [master] Update cypress snapshots
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/image2.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/non-dav.png
Labels: 3. to review, dependencies

#2511 [stable28] Update cypress snapshots
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/image.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/image2.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/non-dav.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/video.png
Labels: 3. to review, dependencies
