Repository nextcloud/viewer, pull requests merged in 2024-08, with the labels that each got.

#2361 chore: update workflows from templates
  .github/workflows/block-merge-freeze.yml
  .github/workflows/block-unconventional-commits.yml
  .github/workflows/command-compile.yml
  .github/workflows/cypress.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
Labels: 3. to review, dependencies, automated

#2407 [master] Update cypress snapshots
  cypress/snapshots/base/visual-regression.cy.ts/image.png
  cypress/snapshots/base/visual-regression.cy.ts/image2.png
  cypress/snapshots/base/visual-regression.cy.ts/non-dav.png
  cypress/snapshots/base/visual-regression.cy.ts/video.png
Labels: 3. to review, dependencies

#2410 [master] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#2436 chore: upgrade cypress-visual-regression
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/image.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/image2.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/non-dav.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/video.png
  cypress/snapshots/base/visual-regression.cy.ts/image.png
  cypress/snapshots/base/visual-regression.cy.ts/image2.png
  cypress/snapshots/base/visual-regression.cy.ts/non-dav.png
  cypress/snapshots/base/visual-regression.cy.ts/video.png
  package-lock.json
  package.json
Labels: 4. to release, dependencies, backport-request
