Repository nextcloud/viewer, pull requests merged in 2024-03, with the labels that each got.

#2182 [stable28] Bump nextcloud/vue from `8.6.2` to `8.8.1`
  package-lock.json
  package.json
Labels: 3. to review

#2191 chore: update workflows from templates
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/psalm.yml
Labels: 3. to review, dependencies, automated

#2211 [master] Update cypress snapshots
  cypress/snapshots/base/visual-regression.cy.ts/image.png
  cypress/snapshots/base/visual-regression.cy.ts/image2.png
  cypress/snapshots/base/visual-regression.cy.ts/non-dav.png
  cypress/snapshots/base/visual-regression.cy.ts/video.png
Labels: 3. to review, dependencies

#2222 fix(cypress): sharing download test
  cypress/e2e/sharing/download-share-disabled.cy.ts
Labels: bug, regression, 4. to release

#2224 [stable27] fix(cypress): sharing download test
  cypress/e2e/sharing/download-share-disabled.cy.js
Labels: bug, regression, 4. to release

#2241 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#2243 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#2246 Revert "fix(deps): update dependency filerobot-image-editor to ^4.7.0 (stable28)"
  package-lock.json
  package.json
Labels: backport-request

#2248 fix: filerobot-image-editor ^4.7.0
  css/viewer-main.css
  js/index-BXlIyGgR.mjs
  js/index-BXlIyGgR.mjs.map
  js/index-BahqIHTU.mjs
  js/index-BahqIHTU.mjs.map
  js/vendor.LICENSE.txt
  js/viewer-main.mjs
  package-lock.json
  src/components/ImageEditor.vue
Labels: bug, regression, 3. to review, backport-request

#2262 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#2261 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies
