Repository nextcloud/viewer, pull requests merged in 2024-10, with the labels that each got.

#2559 [stable30] Update cypress snapshots
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/image2.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/non-dav.png
Labels: 3. to review, dependencies

#2561 [stable28] Update cypress snapshots
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/image2.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/non-dav.png
Labels: 3. to review, dependencies

#2560 [stable29] Update cypress snapshots
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/image2.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/non-dav.png
Labels: 3. to review, dependencies

#2584 fix: Fix error when viewing current version
  js/logger-BoMrrnoP.chunk.mjs.map
  js/viewer-main.mjs
  js/viewer-main.mjs.map
  src/utils/canDownload.ts
  src/utils/fileUtils.ts
Labels: bug, 3. to review

#2589 fix: Update default editor translations for version 4.8.1
  js/viewer-init.mjs
  js/viewer-init.mjs.map
  src/models/editorTranslations.js
Labels: 4. to release, backport-request
