Repository nextcloud/viewer, pull requests merged in 2025-06, with the labels that each got.

#2812 [master] Update cypress snapshots
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/image.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/image2.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/non-dav.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/video.png
Labels: 3. to review, dependencies

#2845 ci: update node.yml workflow from template
  .github/workflows/node.yml
Labels: dependencies

#2860 chore: Update github actions
  .github/workflows/block-merge-freeze.yml
  .github/workflows/block-unconventional-commits.yml
  .github/workflows/command-compile.yml
  .github/workflows/cypress.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  js/vendor.LICENSE.txt
  psalm.xml
Labels: 3. to review

#2868 [master] Update cypress snapshots
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/image.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/image2.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/non-dav.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/video.png
Labels: 3. to review, dependencies

#2872 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#2895 ci: update npm-audit-fix.yml workflow from template
  .github/workflows/npm-audit-fix.yml
Labels: dependencies

#2896 ci: update reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies
