Repository nextcloud/viewer, pull requests merged in 2025-10, with the labels that each got.

#2967 [stable30] Update cypress snapshots
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/image.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/image2.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/non-dav.png
  cypress/snapshots/base/cypress/e2e/visual-regression.cy.ts/video.png
Labels: 3. to review, dependencies

#2984 build(dep): bump PHP requirement to 8.2
  composer.json
  composer.lock
  psalm.xml
Labels: 3. to review, dependencies

#2983 fix(ImageEditing): controls might hide behind iPadOS home bar
  css/init-CqqFQTg6.chunk.css
  css/viewer-init.css
  js/viewer-init.mjs
  js/viewer-init.mjs.map
  src/components/ImageEditor.vue
Labels: bug, 3. to review, backport-request

#2987 [stable30] fix(ImageEditing): controls might hide behind iPadOS home bar
  css/init-BCKKkBfU.chunk.css
  css/viewer-init.css
  js/viewer-init.mjs
  js/viewer-init.mjs.map
  src/components/ImageEditor.vue
Labels: bug, 3. to review
